# Generated by Django 4.1.3 on 2022-12-05 14:06

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('blog', '0003_alter_car_author'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comment',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create_comment', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('text_comment', models.TextField(verbose_name='Текст комментария')),
                ('status_comment', models.BooleanField(default=True, verbose_name='Видимость комментария')),
                ('author_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('car_post', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_car', to='blog.car', verbose_name='Статья')),
            ],
        ),
    ]
