# Generated by Django 4.1.3 on 2022-12-17 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0007_remove_likecomment_comment_remove_likecomment_user_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='car',
            name='rating',
            field=models.DecimalField(decimal_places=2, default=None, max_digits=3, null=True),
        ),
    ]
