# Generated by Django 4.1.3 on 2022-12-17 10:30

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('blog', '0007_remove_likecomment_comment_remove_likecomment_user_and_more'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='UserCarRelation',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like_post', models.BooleanField(default=False, verbose_name='Лайк поста')),
                ('is_bookmarks_post', models.BooleanField(default=False, verbose_name='Пост в закладке')),
                ('rate', models.PositiveSmallIntegerField(choices=[(1, 'Совсем плохо'), (2, 'Плохо'), (3, 'Нормально'), (4, 'Хорошо'), (5, 'Отлично')], null=True, verbose_name='Личная оценка поста')),
                ('car_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='relation_from_user', to='blog.car', verbose_name='оцениваемый пост')),
                ('user_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценивающий пользователь')),
            ],
            options={
                'verbose_name': 'Отношения пользователя к посту',
            },
        ),
    ]
