# Generated by Django 4.1.3 on 2022-12-23 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('blog', '0008_car_rating'),
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('relatepost', '0002_alter_usercarrelation_options'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeMarkPost',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like_post', models.BooleanField(default=False, verbose_name='Лайк поста')),
                ('is_bookmarks_post', models.BooleanField(default=False, verbose_name='Пост в закладке')),
                ('car_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='blog.car', verbose_name='оцениваемый пост')),
                ('user_relation', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Оценивающий пользователь')),
            ],
            options={
                'verbose_name': 'Лайк/Закладка поста',
                'verbose_name_plural': 'Лайки/закладки к посту',
            },
        ),
        migrations.DeleteModel(
            name='UserCarRelation',
        ),
    ]
