# Generated by Django 4.1.3 on 2022-12-23 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('relatepost', '0003_likemarkpost_delete_usercarrelation'),
    ]

    operations = [
        migrations.CreateModel(
            name='RatingStar',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('value', models.SmallIntegerField(default=0, verbose_name='Значение')),
            ],
            options={
                'verbose_name': 'Звезда рейтинга',
                'verbose_name_plural': 'Звёзды рейтинга',
                'ordering': ['-value'],
            },
        ),
    ]
