# Generated by Django 4.1.3 on 2022-12-29 08:43

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0002_videoyoutuberutube_delete_videoyt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='videoyoutuberutube',
            options={'ordering': ['-time_update'], 'verbose_name': 'Видеофайл c YouTube/RuTube', 'verbose_name_plural': 'Видеофайл c YouTube/RuTube'},
        ),
        migrations.CreateModel(
            name='CommentVideoYtRt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('time_create', models.DateTimeField(auto_now_add=True, verbose_name='Время создания комментария')),
                ('text_comment', models.TextField(verbose_name='Текст комментария')),
                ('status_comment', models.BooleanField(default=True, verbose_name='Видимость комментария')),
                ('author_comment', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Автор комментария')),
                ('video', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comment_video', to='video.videoyoutuberutube', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Комментарий к видео',
                'verbose_name_plural': 'Комментарии к видео',
                'ordering': ['time_create'],
            },
        ),
    ]
