# Generated by Django 4.1.3 on 2022-12-30 08:32

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0003_alter_videoyoutuberutube_options_commentvideoytrt'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='commentvideoytrt',
            options={'ordering': ['-time_create'], 'verbose_name': 'Комментарий к видео', 'verbose_name_plural': 'Комментарии к видео'},
        ),
        migrations.CreateModel(
            name='LikeMarkVideo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('is_like_video', models.BooleanField(default=False, verbose_name='Лайк видео')),
                ('is_bookmarks_video', models.BooleanField(default=False, verbose_name='Видео в закладки')),
                ('user_lm_video', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Пользователь')),
                ('video_lm', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='video_to_lmv', to='video.videoyoutuberutube', verbose_name='Видео')),
            ],
            options={
                'verbose_name': 'Лайк/Закладка видео',
                'verbose_name_plural': 'Лайки/закладки к видео',
            },
        ),
    ]
