# Generated by Django 4.1.3 on 2022-12-31 09:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('video', '0004_alter_commentvideoytrt_options_likemarkvideo'),
    ]

    operations = [
        migrations.CreateModel(
            name='LikeCommentVideoYtRt',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('comment', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='video.commentvideoytrt', verbose_name='Лайкнутый комментарий')),
                ('user', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL, verbose_name='Лайкнувший пользователь')),
            ],
            options={
                'verbose_name': 'Лайк комментария к видео',
                'verbose_name_plural': 'Лайки комментариев к видео',
            },
        ),
    ]
